version: "3"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: 16
    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    network_mode: host

  opa:
    image: openpolicyagent/opa:latest-debug
    command: run --server --skip-verify --watch --log-level debug /rego
    volumes:
      - type: bind
        source: ../opa/rego
        target: /rego
    ports:
      - 8182:8181
